# Generated by Django 4.2.4 on 2023-11-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='SaveContactMessage',
        ),
    ]
