# Generated by Django 4.2.4 on 2023-11-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(upload_to='./media/'),
        ),
    ]
