# Generated by Django 4.2.4 on 2023-11-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_alter_skills_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='works',
            name='image',
            field=models.ImageField(null=True, upload_to='works/'),
        ),
    ]
