# Generated by Django 4.2.4 on 2023-11-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_project_image_works_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='certificate',
            field=models.ImageField(null=True, upload_to='certificates/'),
        ),
    ]
