# Generated by Django 4.2.4 on 2023-11-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_courses_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
