# Generated by Django 4.2.4 on 2023-11-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_alter_courses_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='works/'),
        ),
    ]
